### ISSUE TITLE
docker image error

### ISSUE THREAD

**Issue by Lbookman** [preinh/karma-config-base#1]
I get this error when trying to build a docker image. Does it have to do with the service being down again?
[ERROR] Failed to execute goal on project commands-bloom: Could not resolve dependencies for project edu.isi:commands-bloom:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [edu.isi:commands-alignment-openrdf:jar:0.0.1-SNAPSHOT (compile), edu.isi:commands-python:jar:0.0.1-SNAPSHOT (compile), edu.isi:commands-alignment:jar:0.0.1-SNAPSHOT (compile), org.apache.hadoop:hadoop-common:jar:2.4.0.2.1.3.0-563 (compile)]: Failed to read artifact descriptor for org.apache.hadoop:hadoop-common:jar:2.4.0.2.1.3.0-563: Could not transfer artifact org.apache.hadoop:hadoop-common:pom:2.4.0.2.1.3.0-563 from/to HDPReleases (http://repo.hortonworks.com/content/repositories/releases/): Failed to transfer file: http://repo.hortonworks.com/content/repositories/releases/org/apache/hadoop/hadoop-common/2.4.0.2.1.3.0-563/hadoop-common-2.4.0.2.1.3.0-563.pom. Return code is: 500 , ReasonPhrase:Server Error. -> [Help 1]
[ERROR]

**Comment by preinh** [comment]
Hi @Lbookman ,
Is this problem persisting? I hope they don't! Sorry for do not answer you earlier.

It seems like an error at the dependency provider server and could be corrected after some time.

As this karma-config-base project installs a development version of karma, some dependencies could be temporarily broken.
